# Generated by Django 2.2.20 on 2021-08-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210825_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Our door', 'Our door')], max_length=200, null=True),
        ),
    ]
